ElMaitre.Web3/Controllers/ServiceController.cs
using ElMaitre.DAL.Data;
using ElMaitre.DAL.Models;
using ElMaitre.DTO;
using ElMaitre.Web.Extensions;
using ElMaitre.Web.Filters;
using ElMaitre.Web.Helpers;
using ElMaitre.Web.Models;
using ElMaitre.Web.ViewModels;
using ElMaitre.Web3.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using System;
using System.Diagnostics;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Net.Http;
using System.Security.Claims;
using System.Security.Principal;
using System.Text;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace ElMaitre.Web3.Controllers
{
    public class ServiceController : BaseController
    {
        private AppSettings AppSettings { get; set; }
        ApplicationDbContext con;
        public ServiceController(IOptions<AppSettings> settings, ApplicationDbContext con)
        {
            AppSettings = settings.Value;
            this.con = con;
        }

        [Route("/Service/Index")]
        public async Task<IActionResult> Index(string hmac, int merchant_order_id, 
            string created_at, string currency, bool is_refund, int txn_response_code, int profile_id, 
            bool success, int order, int id, int amount_cents)
        {
            if (hmac != null)
            {
                var token = Request.Cookies["token"];
                string apiUrl = $"http://{Request.Host}/api/ServiceApi/UpdateOrd/{merchant_order_id}/{hmac}/{created_at}/{currency}/{is_refund}/{txn_response_code}/{profile_id}/{success}/{order}/{id}/{amount_cents}";

                using (HttpClient client = new HttpClient())
                {
                    client.BaseAddress = new Uri(apiUrl);
                    client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                    client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

                    HttpResponseMessage response = await client.GetAsync(apiUrl);
                    if (response.IsSuccessStatusCode)
                    {
                        var data = await response.Content.ReadAsStringAsync();
                        var result = JsonConvert.DeserializeObject<BookSessionResult>(data);

                    }
                    else if (response.StatusCode == System.Net.HttpStatusCode.Unauthorized)
                    {
                        return null;
                    }
                }
            }

            //return View(new BaseViewModel(Request));
            //return View(con.Orders.FirstOrDefault(o => o.merchant_order_id == merchant_order_id).lawyer);
            var bm = new BaseViewModel(Request);
            bm.Lawyer = con.Orders.Include("lawyer").Include("lawyer.User").FirstOrDefault(o => o.merchant_order_id == merchant_order_id).lawyer;
            return View(bm);
        }

        [Route("/Service/Index/{serviceId}/{lawyerId}")]
        public IActionResult Index(int serviceId, int lawyerId)
        {
            //return View(new BaseViewModel(Request));
            return View(new BaseViewModel(Request));
        }

        string redirectUrl;
        string fToken;
        int order_id;
        [HttpPost]
        [Route("/Service/PayAction/{serviceId}/{lawyerId}/{pType}")]
        public async Task<IActionResult> PayAction(int serviceId, int lawyerId, int pType, int type_drp)
        {
            var res = await GetToken(type_drp * 100, pType == 1 ? AppSettings.PaymentIntegrationId : AppSettings.PaymentIntegrationIdCash);
            var token = Request.Cookies["token"];
            string apiUrl = $"http://{Request.Host}/api/ServiceApi/NewOrd/{serviceId}/{lawyerId}/{order_id}";
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiUrl);
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

                HttpResponseMessage response = await client.GetAsync(apiUrl);
                if (response.IsSuccessStatusCode)
                {
                    var data = await response.Content.ReadAsStringAsync();
                    var result = JsonConvert.DeserializeObject<BookSessionResult>(data);

                }
                else if (response.StatusCode == System.Net.HttpStatusCode.Unauthorized)
                {
                    return null;
                }
            }
            //Redirect("http://accept.paymobsolutions.com/api/acceptance/iframes/7127?payment_token=" + fToken);
            //return View(new BaseViewModel(Request));
            //return (Redirect("http://accept.paymobsolutions.com/api/acceptance/iframes/7127?payment_token=" + fToken));
            if (pType == 1)
            {
                return Ok(new { token = fToken, ptype = pType });
            }
            else
            {
                return Ok(new { redirect_url = redirectUrl, ptype = pType });
            }
        }

        [Route("/Service/PayWithCard/{serviceId}/{lawyerId}")]
        public async Task<IActionResult> PayWithCard(int serviceId, int lawyerId)
        {
            var details = await GetServiceDetails(serviceId, lawyerId);
            if (details != null && details.CanReserved)
            {
                var res = await GetToken(1, 4255);
                var order = await OrderCreation(res.Token, res.Profile.Id, details.Price * 100, 4255);
                var pkey = await GetPaymentKey(res.Token, order.Id, details.Price * 100, 4255);

                if (!string.IsNullOrEmpty(pkey.Token))
                {
                    var bookRes = await PayService(serviceId, lawyerId, order.Id);
                    if (bookRes == null)
                        return RedirectToAction("Login", "Account");


                    var iframeId = AppSettings.PaymentIframeId;
                    return Redirect($"http://accept.paymobsolutions.com/api/acceptance/iframes/{iframeId}?payment_token={pkey.Token}");
                }
            }
            return null;
        }

        private async Task<ServiceDTO> GetServiceDetails(int serviceId,int lawyerId)
        {
            var token = Request.Cookies["token"];
            string apiUrl = $"http://{Request.Host}/api/ServiceApi/Get/{serviceId}/{lawyerId}";

            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiUrl);
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

                HttpResponseMessage response = await client.GetAsync(apiUrl);
                if (response.IsSuccessStatusCode)
                {
                    var data = await response.Content.ReadAsStringAsync();
                    var result = JsonConvert.DeserializeObject<ServiceDTO>(data);
                    return result;
                }
            }
            return null;
        }

        private async Task<PaymentTokenResult> GetToken(double price, int integration_Id)
        {
            string apiUrl = "http://accept.paymobsolutions.com/api/auth/tokens";
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiUrl);
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                var paymentApiKey = AppSettings.PaymentApiKey;
                var bodyJS = JsonConvert.SerializeObject(new { api_key = paymentApiKey });
                var body = new StringContent(bodyJS, Encoding.UTF8, "application/json");
                HttpResponseMessage response = await client.PostAsync(apiUrl, body);
                if (response.IsSuccessStatusCode)
                {
                    var data = await response.Content.ReadAsStringAsync();
                    var result = JsonConvert.DeserializeObject<PaymentTokenResult>(data);
                    await OrderCreation(result.Token, AppSettings.MerchantId, price, integration_Id);
                    return result;
                }
            }
            return null;
        }

        private async Task<OrderResult> OrderCreation(string token, long merchantId, double amount
            , int integration_Id)
        {
            string apiUrl = $"http://accept.paymobsolutions.com/api/ecommerce/orders";
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiUrl);
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

                var ordId = Utilities.GetUniqueKeyNums(6);
                order_id = int.Parse(ordId);
                var bodyJS = JsonConvert.SerializeObject(new
                {
                    auth_token = token,
                    delivery_needed = false,
                    merchant_id = merchantId,
                    amount_cents = amount,
                    currency = "EGP",
                    //merchant_order_id = Guid.NewGuid().ToString()
                    merchant_order_id = ordId
                });
                var body = new StringContent(bodyJS, Encoding.UTF8, "application/json");

ElMaitre.Web3/Views/Service/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer
@{
    ViewData["Title"] = Localizer["title"];
}



<style>

    .cd-auto-hide-header {
        background-color: #ffffff
    }
</style>
<section id="header_image_inner">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="main-ttl inner_pages_ttl text-center my-4 py-3">
                    <h2>@Localizer["title"]</h2>
                </div>
            </div>
        </div>
    </div>
</section>
@{
    Microsoft.Extensions.Primitives.StringValues queryVal;
    if (Context.Request.Query.TryGetValue("amount_cents", out queryVal))
    {
    }
}
@if (queryVal.FirstOrDefault() != null)
{
    var val = double.Parse(queryVal.FirstOrDefault()) / 100;
    <p></p>


    <div class="alert alert-success alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>تمت عملية الدفع بنجاح</strong>
        <strong>@val جم</strong>
    </div>
    <hr />
    <div class="alert alert-info">
        <span>المحامى <strong>@Model.Lawyer.User.Name</strong></span>
        <br />
        <span>الهاتف <strong>@Model.Lawyer.User.PhoneNumber</strong></span>
    </div>
}
else
{

<div class="inner_pages">
    <section class="services-page">
        <div class="container">
            <div class="services-content my-5">
                <div class="row">
                    <div class="col-md-9">
                        <div class="services-desc  p-4">
                            <div class="pricing-title mb-4">
                                <h3 data-bind="text: service().Title"></h3>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="d-flex align-items-center">
                                        <i class="far fa-clock mr-1" style="margin-left:7px;"></i>
                                        <h6 class="mb-0 font-weight-bold">@Localizer["Duration"]</h6>
                                    </div>
                                </div>
                                <div class="col-md-8">
                                    <p data-bind="text: service().Duration"></p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="d-flex align-items-center">
                                        <i class="fas fa-phone mr-1" style="margin-left:7px;"></i>
                                        <h6 class="mb-0 font-weight-bold">@Localizer["Contact"]</h6>
                                    </div>
                                </div>
                                <div class="col-md-8">
                                    <p data-bind="text: service().ContactNumber"></p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="d-flex align-items-center">
                                        <i class="far fa-file-alt mr-1" style="margin-left:7px;"></i>
                                        <h6 class="mb-0 font-weight-bold">@Localizer["Paperwork"]</h6>
                                    </div>
                                </div>
                                <div class="col-md-8">
                                    <ul class="p-0" data-bind="foreach: paperWork">
                                        <li data-bind="text: $data"></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="d-flex align-items-center">
                                        <i class="far fa-file-alt mr-1" style="margin-left:7px;"></i>
                                        <h6 class="mb-0 font-weight-bold">@Localizer["Steps"]</h6>
                                    </div>
                                </div>
                                <div class="col-md-8">
                                    <ul class="p-0">
                                        <li> بعد دفع قيمة الخدمة،سيظهرلك علي الشاشة تفاصيل إكمال التوكيل للمحامي و بياناته كما سيظهرلك أرقام المحامي المختلفة وجميع بيانات الاتصال به.</li>
                                        <li>
                                             سيقوم أحد أفراد خدمة عملاء "محامي.كو" بالتواصل معك في اسرع وقت لشرح تفاصيل أداة الخدمة
                                            والرد على جميع استفساراتك بخصوص الخدمة المقدمة.
                                        </li>
                                        <li> ستتابع شركة "محامي.كو" جميع خطوات تقديم الخدمة مع المحامي المختار من العميل وفقاً للقواعد المتعارف عليها مهنياً حتى إنتهاء الخدمة.</li>
                                        <li> إذا تم مخالفة أي من هذه البنود ستقوم شركة "محامي.كو" برد كامل المبلغ المدفوع للعميل أو (إذا أراد العميل)  باختيار محامي أخر لأداة الخدمة.</li>
                                    </ul>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="col-md-3 d-flex align-items-center justify-content-center pricing-action-content">
                        <div class="pricing-action-area w-100">
                            <div class="pricing-price">
                                <span id="PriceType1" style="font-size:15px !important;"></span>
                                <span class="price-unit" id="PriceLawyer" data-bind="text: service().PriceLawyer"></span>
                                <button type="button" class="btn btn-primary" hidden id="PriceLawyerbtn" data-toggle="modal" data-target="#pay1ModalCenter">
                                    @Localizer["Pay"]
                                </button>

                                <hr  hidden />
                                <span id="PriceType2" style="font-size:15px !important;"></span>
                                <span class="price-unit" id="PriceLevel2Lawyer" data-bind="text: service().PriceLevel2Lawyer"></span>
                                <button type="button" class="btn btn-primary" hidden id="PriceLevel2Lawyerbtn" data-toggle="modal" data-target="#pay1ModalCenter">
                                    @Localizer["Pay"]
                                </button>

                            </div>
                        </div>

                    </div>
                </div>

            </div>
        </div>

    </section>
</div>

    <div class="modal fade" id="pay1ModalCenter" tabindex="-1" role="dialog" aria-labelledby="pay1ModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="pay1ModalCenterTitle">@Localizer["Pay"]</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                @*<div class="modal-body">
                        ...
                    </div>*@
                <div class="modal-footer">
                    @*<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>*@
                    <form asp-controller="Service" asp-action="PayAction" data-ajax-begin="AjaxBegin" data-ajax-complete="AjaxComplete" data-ajax="true" data-ajax-method="POST"
                          asp-route-pType="1" id="frm1" data-ajax-mode="replace" data-ajax-update="#content">
                        <input type="hidden" value="1" name="type_drp"
                                    id="type_drp"/>
                        @*<select class="form-control" name="type_drp"
                                    id="type_drp" style="padding:0 !important">
                                <option data-bind="value: service().PriceLawyer" selected="selected">
                                    @Localizer["PriceLawyer"]
                                </option>
                                <option data-bind="value: service().PriceLevel2Lawyer">@Localizer["PriceLevel2Lawyer"]</option>
                            </select>*@

                        <button class="btn btn-secondary" type="submit">
                            <i class="far fa-money-bill-alt"></i>
                            بطاقة ائتمان


                        </button>
                    </form>
                    @*<button type="button" class="btn btn-secondary" data-dismiss="modal">بطاقة ائتمان</button>*@
                    @*<button type="button" class="btn btn-primary">دفع فورى</button>*@

                    <form asp-controller="Service" asp-action="PayAction"
                          asp-route-pType="2" data-ajax-begin="AjaxBegin" data-ajax-complete="AjaxComplete" data-ajax="true" data-ajax-method="POST"
                          data-ajax-mode="replace" id="frm2" data-ajax-update="#content">
                        <input type="hidden" value="2" name="type_drp"
                               id="type_drp" />

                        @*<select class="form-control" name="type_drp"
                id="type_drp" style="padding:0 !important">
            <option data-bind="value: service().PriceLawyer" selected="selected">
                @Localizer["PriceLawyer"]
            </option>
            <option data-bind="value: service().PriceLevel2Lawyer">@Localizer["PriceLevel2Lawyer"]</option>
        </select>*@

                        <button class="btn btn-secondary" type="submit">
                            <i class="far fa-money-bill-alt"></i>
                            كاش وانت فى مكانك لأى حد من مندوبينا

                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
    <div class="modal fade" id="pay2ModalCenter" tabindex="-1" role="dialog" aria-labelledby="pay2ModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="pay2ModalCenterTitle">@Localizer["Pay"]</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                @*<div class="modal-body">
                    ...
                </div>*@
                <div class="modal-footer">
                    @*<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>*@
                    <form asp-controller="Service" asp-action="PayAction" data-ajax-begin="AjaxBegin" data-ajax-complete="AjaxComplete" data-ajax="true" data-ajax-method="POST"
                          asp-route-pType="1" id="frm1" data-ajax-mode="replace" data-ajax-update="#content">
                        <input type="hidden" value="1" name="type_drp"
                               id="type_drp" />

                        @*<select class="form-control" name="type_drp"
                id="type_drp" style="padding:0 !important">
            <option data-bind="value: service().PriceLawyer" selected="selected">
                @Localizer["PriceLawyer"]
            </option>
            <option data-bind="value: service().PriceLevel2Lawyer">@Localizer["PriceLevel2Lawyer"]</option>
        </select>*@

                        <button class="btn btn-secondary" type="submit">
                            <i class="far fa-money-bill-alt"></i>
                            بطاقة ائتمان


                        </button>
                    </form>
                    @*<button type="button" class="btn btn-secondary" data-dismiss="modal">بطاقة ائتمان</button>*@
                    @*<button type="button" class="btn btn-primary">دفع فورى</button>*@

                    <form asp-controller="Service" asp-action="PayAction"
                          asp-route-pType="2" data-ajax-begin="AjaxBegin" data-ajax-complete="AjaxComplete" data-ajax="true" data-ajax-method="POST"
                          data-ajax-mode="replace" id="frm2" data-ajax-update="#content">
                        <input type="hidden" value="2" name="type_drp"
                               id="type_drp" />

                        @*<select class="form-control" name="type_drp"
                id="type_drp" style="padding:0 !important">
            <option data-bind="value: service().PriceLawyer" selected="selected">
                @Localizer["PriceLawyer"]
            </option>
            <option data-bind="value: service().PriceLevel2Lawyer">@Localizer["PriceLevel2Lawyer"]</option>
        </select>*@

                        <button class="btn btn-secondary" type="submit">
                            <i class="far fa-money-bill-alt"></i>
                            كاش وانت فى مكانك لأى حد من مندوبينا

                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
}



@Html.Partial("~/Views/Shared/UserNotification.cshtml")
<script src="~/app/services.js"></script>
<script src="~/app/ServicePaymentAction.js"></script>